import { LayoutLabels } from "./layouts";

export const SECTION_TITLES: Record<string, LayoutLabels> = {
  en: {
    summary: "Summary",
    experience: "Experience",
    education: "Education",
    skills: "Skills",
    tech: "Tech",
    standaloneTech: "Tech Skills",
    soft: "Soft",
    standaloneSoft: "Soft Skills",
    languages: "Languages",
    contact: "Contact",
    profile: "Profile",
    clients: "Clients",
  },
  es: {
    summary: "Resumen",
    experience: "Experiencia",
    education: "Educación",
    skills: "Habilidades",
    tech: "Técnicas",
    standaloneTech: "Habilidades Técnicas",
    soft: "Blandas",
    standaloneSoft: "Habilidades Blandas",
    languages: "Idiomas",
    contact: "Contacto",
    profile: "Perfil",
    clients: "Clientes",
  },
  ca: {
    summary: "Resum",
    experience: "Experiència",
    education: "Educació",
    skills: "Habilitats",
    tech: "Tècniques",
    standaloneTech: "Habilitats Tècniques",
    soft: "Toves",
    standaloneSoft: "Habilitats Toves",
    languages: "Idiomes",
    contact: "Contacte",
    profile: "Perfil",
    clients: "Clients",
  },
  fr: {
    summary: "Résumé",
    experience: "Expérience",
    education: "Formation",
    skills: "Compétences",
    tech: "Techniques",
    standaloneTech: "Compétences Techniques",
    soft: "Comportementales",
    standaloneSoft: "Compétences Comportementales",
    languages: "Langues",
    contact: "Contact",
    clients: "Clients",
    profile: "Profil",
  },
};
